_target_: pytorch_lightning.Trainer

accelerator: "gpu"
# accelerator: "cpu"
# gpus: 1
devices: 4

min_epochs: 25
max_epochs: 30

# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 1

# ckpt path
# resume_from_checkpoint: null

check_val_every_n_epoch: 1
val_check_interval: 1.0

# Uncomment to not run validation set - If limit_val_batches is set to 0.0, ensure the "monitor" argument in default.yaml (callback config file) is not set to "validation/loss". 
# limit_val_batches: 0.0